Host the app on Heroku PaaS
MakeWish/makewishsite pull request #3
Opened 2019-10-11 09:58 UTC by HabibSentongo

## What does this PR do?
Hosts the app on Heroku platform.
### Description of Task to be completed?
* Create app on Heroku and connect it with GH-Repo
* Add Procfile to the repo
### How should this be manually tested
* Visit this link [here](https://makewishtech.herokuapp.com)
### What are the relevant pivotal tracker stories?
[#169009249](https://www.pivotaltracker.com/n/projects/2399962/stories/169009249)
### Screenshots.
![image](https://user-images.githubusercontent.com/39903548/66642867-401c0000-ec26-11e9-88df-a2f2a0eab686.png)

2019-10-11 10:18 UTC, NicholusMuwonge commented on Procfile
> +web: vendor/bin/heroku-php-apache2 public/
Add an empty line here

2019-10-11 10:21 UTC, NicholusMuwonge requested changes
Since this site will further be expanded to use backend services, like a database, did you cater for that in this story?

`It's not feedback but it would be nice to use a URL shortener for the hosted site`

2019-10-11 11:08 UTC, HabibSentongo commented on Procfile
> +web: vendor/bin/heroku-php-apache2 public/
This has been resolved

2019-10-17 09:58 UTC, reifred approved these changes

2019-10-17 09:59 UTC, NicholusMuwonge approved these changes

2019-10-17 13:14 UTC, merged